import { NextResponse } from "next/server"
import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import { COMPANY_INFO, STATS, SERVICES, FMCSA_LINKS } from "@/lib/constants"

/**
 * One-click carrier snapshot for brokers (marketing side).
 *
 * A broker vetting a carrier in Highway / MyCarrierPackets / RMIS / Carrier411
 * wants MC + USDOT + insurance + equipment on ONE page they can drop in the
 * file while the full signed packet (W-9, COI, agreement) comes over by email
 * — that half stays human-sent via the existing request form, because a COI
 * is issued per-broker by the insurer and a generic one on a public URL
 * invites fraud. Everything printed here is public, verifiable fact.
 *
 * Deliberately independent of src/lib/hub/packet.ts: that vault serves
 * authenticated carriers' real documents; this route serves Thind's public
 * snapshot from constants, with no database and no tenant.
 */

const INK = rgb(0.09, 0.1, 0.12)
const GRAY = rgb(0.42, 0.45, 0.48)
const SIGNAL = rgb(0.83, 0.19, 0.14)

export const dynamic = "force-static"

export async function GET() {
  const doc = await PDFDocument.create()
  const page = doc.addPage([612, 792]) // US Letter
  const regular = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  let y = 740
  const text = (
    value: string,
    opts: { x?: number; size?: number; boldFace?: boolean; color?: ReturnType<typeof rgb> } = {}
  ) => {
    page.drawText(value, {
      x: opts.x ?? 48,
      y,
      size: opts.size ?? 10.5,
      font: opts.boldFace ? bold : regular,
      color: opts.color ?? INK,
    })
  }
  const gap = (n: number) => {
    y -= n
  }

  text(COMPANY_INFO.name.toUpperCase(), { size: 22, boldFace: true })
  gap(16)
  text("CARRIER SNAPSHOT — FOR BROKER ONBOARDING", { size: 9, color: SIGNAL, boldFace: true })
  gap(24)
  text(
    `Asset-based FMCSA-authorized carrier · ${COMPANY_INFO.location} · family-run since ${COMPANY_INFO.founded}`,
    { size: 10, color: GRAY }
  )
  gap(30)

  const row = (label: string, value: string) => {
    text(label.toUpperCase(), { size: 8.5, color: GRAY, boldFace: true })
    text(value, { x: 200, size: 10.5, boldFace: true })
    gap(19)
  }

  row("USDOT", COMPANY_INFO.dot)
  row("MC", COMPANY_INFO.mc)
  row("Legal name", `${COMPANY_INFO.name} LLC`)
  row("Owner", COMPANY_INFO.owner)
  row("Address", COMPANY_INFO.address)
  row("Phone (dispatch)", COMPANY_INFO.phone)
  row("Email", COMPANY_INFO.email)
  row("Authority since", String(COMPANY_INFO.founded))
  row("Power units", `${STATS.trucksInFleet} (2020-2022 Freightliner Cascadias)`)
  row("Equipment", SERVICES.types.join(" · "))
  row("Coverage", `${STATS.statesCovered} states (lower 48)`)
  row("Auto liability", "$1,000,000")
  row("Cargo", "$100,000")
  gap(10)

  text("VERIFY US FIRST", { size: 9, color: SIGNAL, boldFace: true })
  gap(16)
  text("FMCSA SAFER company snapshot (search USDOT " + COMPANY_INFO.dot + "):", { size: 9.5 })
  gap(14)
  text(FMCSA_LINKS.safer, { size: 9.5, color: GRAY })
  gap(26)

  text("FULL PACKET (W-9, COI, SIGNED AGREEMENT)", { size: 9, color: SIGNAL, boldFace: true })
  gap(16)
  const lines = [
    "Certificates of insurance are issued per broker by our insurer, so the signed packet",
    "comes from a person, not a public link: request it at thindtransport.com/brokers or",
    `call dispatch at ${COMPANY_INFO.phone} — same-business-day turnaround. Factoring NOA,`,
    "if applicable to your setup, is included with the packet.",
  ]
  for (const line of lines) {
    text(line, { size: 9.5, color: GRAY })
    gap(13)
  }

  gap(18)
  text(`Generated by thindtransport.com · ${COMPANY_INFO.name} LLC · USDOT ${COMPANY_INFO.dot} · MC ${COMPANY_INFO.mc}`, {
    size: 8,
    color: GRAY,
  })

  const bytes = await doc.save()
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      "content-type": "application/pdf",
      "content-disposition": 'attachment; filename="thind-transport-carrier-snapshot.pdf"',
      "cache-control": "public, max-age=86400",
    },
  })
}
